version: "3.8"

services:
  sanity:
    ports:
      - 8333:3333
    volumes:
      - ./sanity:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "yarn global add @sanity/cli && sanity start --host=0.0.0.0"
